name: my-first-workflow
# Reusable Workflow for CI Pipeline
on:
    workflow_call:
        secrets:
            SONAR_TOKEN:
                required: true
            DOCKERHUB_USERNAME:
                required: true
            DOCKERHUB_TOKEN:
                required: true
jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      # ! download the repo
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Set up Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          mkdir reports/
          # ! genrating the reports on new reports folder and then uploading that folder as artifact to github actions and then we can download that artifact and see the reports of unit tests and code coverage
          pytest --junitxml=reports/test-results.xml --cov=./ --cov-report=xml:reports/coverage.xml --cov-report=term-missing -v
      - name: Upload test results
        uses: actions/upload-artifact@v5.0.0
        with:
          name: unit-test-results
          path: reports/
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      # 
      # ! this is required to upload the results of codeql analysis to github security tab
    strategy:
      matrix:
        language: ['python']
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Initialize CodeQL
      # ! code ql is used for static code analysis and to find security vulnerabilities in the code
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - name : Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with :
          category: 'security'
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name : Download Coverage Report
        uses: actions/download-artifact@v5.0.0
        with:
          name: unit-test-results
          path: .
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # ! solving sonarqube qualtiy gate check failure by adding SONAR_TOKEN in secrets and then using it here to authenticate with sonarqube server and upload the results of code analysis to sonarqube server
      # ! checks for status of code analysis and if it fails then it will fail the workflow and if it passes then it will pass the workflow
      - name : SonarQube Quality Gate Check
        uses : SonarSource/sonarqube-quality-gate-action@v1.1.0
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}         

  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs: [codeql, sonarqube]
    if: success()
    outputs:
      image-tag: ${{ steps.vars.outputs.IMAGE_TAGS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name : Generate image tag
        id: vars
        run : |
          IMAGE_TAGS="${{github.run_id}}-${GITHUB_SHA::7}"
          echo "IMAGE_TAGS=$IMAGE_TAGS" >> $GITHUB_OUTPUT
      - name: Build Image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          # ! we are not pushing the image to docker hub or any other registry we are just building the image and then saving that image as artifact in github actions and then we can download that artifact and load that image in our local docker and then run that image in our local docker and then test that image in our local docker and then if everything is fine then we can push that image to docker hub or any other registry
          load: true
          # ! using the image tags
          tags: myapp:${{ steps.vars.outputs.IMAGE_TAGS }}
      - name : Save Docker Image 
        run : |
          docker save myapp:${{ steps.vars.outputs.IMAGE_TAGS }} -o myapp_${{ steps.vars.outputs.IMAGE_TAGS }}.tar
      - name : Upload Docker Image Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: docker-image-upload
          path: myapp_${{ steps.vars.outputs.IMAGE_TAGS }}.tar
  publish-dockerhub:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    if: success()
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: docker-image-upload
          path: .
      - name: Load Docker Image
        run: |
          docker load -i myapp_${{ needs.build.outputs.image-tag }}.tar
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: TAG Image
        run: |
          docker tag myapp:${{ needs.build.outputs.image-tag }} ${{secrets.DOCKERHUB_USERNAME}}/myapp:${{ needs.build.outputs.image-tag }}
      - name : Push Image
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/myapp:${{ needs.build.outputs.image-tag }}
  
  publish-ghcr:
    name: Publish to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: build
    if: success()
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: docker-image-upload
          path: .
      - name: Load Docker Image
        run: |
          docker load -i myapp_${{ needs.build.outputs.image-tag }}.tar
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # ! using github actor to login to github container registry and then using GITHUB_TOKEN to authenticate with github container registry and then push the image to github container registry and then we can use that image in our kubernetes deployment yaml file and then we can deploy that image to kubernetes cluster
          # * ! we can also use personal access token to authenticate with github container registry and then push the image to github container registry but using GITHUB_TOKEN is more secure and recommended way to authenticate with github container registry and then push the image to github container registry
          # ! GITHUB_TOKEN is a special token that is automatically generated by github actions for each workflow run and it has limited permissions and it is only valid for the duration of the workflow run and it is automatically revoked after the workflow run is completed and it is more secure than using personal access token because personal access token can be leaked and can be used by attackers to access the github container registry and push malicious images to github container registry but GITHUB_TOKEN is automatically revoked after the workflow run is completed so even if it is leaked it cannot be used by attackers to access the github container registry and push malicious images to github container registry
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: TAG Image
        run: |
          docker tag myapp:${{ needs.build.outputs.image-tag }} ghcr.io/${{ github.actor }}/myapp:${{ needs.build.outputs.image-tag }}
      - name : Push Image
        run: |
          docker push ghcr.io/${{ github.actor }}/myapp:${{ needs.build.outputs.image-tag }}
      